<a href="https://colab.research.google.com/github/georgievw/ML/blob/main/%D0%A1%D0%9B%D0%90%D0%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Часть 1


In [ ]:
#Реализация метода Гаусса решения СЛАУ
def Gauss(A, b: np.ndarray) -> np.ndarray:
  n = A.shape[0]
  for i in range(0, n-1):
    for j in range(i+1, n):
      k = A[j,i]/A[i,i]
      A[j] = A[j] - k*A[i]
      b[j] = b[j] - k*b[i]
  for i in reversed(range(1, n)):
    for j in reversed(range(0, i)):
      k = A[j,i]/A[i,i]
      A[j] = A[j] - k*A[i]
      b[j] = b[j] - k*b[i]
  for i in range(0, n):
    b[i] = b[i] / A[i,i]
    A[i] = A[i] / A[i,i]
  return(b)

In [ ]:
#Хорошо обусловленная матрица
A = np.array([[31.2000,        -1.3200,        -7.6800,         4.0900], 
     [7.2300,      -126.0000,         7.1400,         3.0400],     
     [9.4900,         6.4000,         6.0000,         8.4500],     
     [2.6800,        -3.2900,         0.2800,        13.4000]])
x = np.array([[10],
     [1],
     [30],
     [-40]])
b = np.array([[-83.3200],
     [38.9000],
     [-56.7000],
     [-504.0900]])

In [ ]:
#Результаты, полученные при использовании реализованного метода Гаусса
x_pred = Gauss(A.copy(), b.copy())
x_pred

array([[ 10.],
       [  1.],
       [ 30.],
       [-40.]])

In [ ]:
#Нормы невязок при хорошо обусловленной матрице
print(np.linalg.norm(b - np.dot(A, x_pred), 1))
print(np.linalg.norm(b - np.dot(A, x_pred), np.inf))

1.9184653865522705e-13
1.1368683772161603e-13


In [ ]:
#Погрешности при хорошо обусловленной матрице
print(np.linalg.norm(x, 1) - np.linalg.norm(x_pred, 1))
print((np.linalg.norm(x, 1) - np.linalg.norm(x_pred, 1))/np.linalg.norm(x, 1))

2.842170943040401e-14
3.50885301609926e-16


In [ ]:
#Сравнение с результатами полученными при использовании встроенной процедуры
np.linalg.solve(A, b) - x_pred

array([[1.77635684e-15],
       [1.11022302e-15],
       [7.10542736e-15],
       [0.00000000e+00]])

In [ ]:
#Обратная матрица, полученная при использовании реализованного метода Гаусса
A_inv = Gauss(A.copy(),np.eye(4))
A_inv

array([[ 0.02465987,  0.00199842,  0.03045515, -0.02718508],
       [-0.00051963, -0.00741936,  0.00832289, -0.00340658],
       [-0.03227363,  0.00812046,  0.11881585, -0.06691649],
       [-0.00438518, -0.00239099, -0.00653029,  0.08062574]])

In [ ]:
#Проверка
np.dot(A, A_inv)

array([[ 1.00000000e+00,  4.26515622e-19, -5.63525584e-17,
         3.48942038e-17],
       [-4.70627157e-17,  1.00000000e+00, -9.11378688e-18,
        -1.21480577e-16],
       [-9.13398342e-17,  7.33674854e-18,  1.00000000e+00,
         6.34487166e-17],
       [ 2.37690332e-17, -2.58417210e-18,  1.64149867e-17,
         1.00000000e+00]])

In [ ]:
#Числа обусловленности матрицы
print(np.linalg.cond(A, p=1))
print(np.linalg.cond(A, p=np.inf))

24.40612642282436
32.428790658916036


In [ ]:
#Плохо обусловленная матрица
A = np.array([[16.3820,        -2.0490,       -41.8290,        16.3920],    
      [307.6480,       -38.4660,      -840.3660,       312.5280],      
      [0.4560,        -0.0570,        -1.1770,         0.4560], 
      [23.2720,        -2.9090,       -66.3090,        23.8720]])
x = np.array([[2],
              [60],
              [-1],
              [5]])
b = np.array([[33.6130],
              [710.3420],
              [0.9490],
              [57.6730]])

In [ ]:
#Результаты, полученные при использовании реализованного метода Гаусса
x_pred = Gauss(A.copy(), b.copy())
x_pred

array([[ 1.99999998],
       [59.99999985],
       [-1.        ],
       [ 5.        ]])

In [ ]:
#Нормы невязок при плохо обусловленной матрице
print(np.linalg.norm(b - np.dot(A, x_pred), 1))
print(np.linalg.norm(b - np.dot(A, x_pred), np.inf))

8.081911806456787e-10
7.149765224312432e-10


In [ ]:
#Погрешности при плохо обусловленной матрице
print(np.linalg.norm(x, 1) - np.linalg.norm(x_pred, 1))
print((np.linalg.norm(x, 1) - np.linalg.norm(x_pred, 1))/np.linalg.norm(x, 1))

1.684516917066503e-07
2.4772307603919163e-09


In [ ]:
#Сравнение с результатами полученными при использовании встроенной процедуры
np.linalg.solve(A, b) - x_pred

array([[1.01552367e-09],
       [9.44513090e-09],
       [2.08284501e-11],
       [2.16561880e-10]])

In [ ]:
#Обратная матрица, полученная при использовании реализованного метода Гаусса
A_inv = Gauss(A.copy(),np.eye(4))
A_inv

array([[-1.09690000e+06,  1.37100000e+05,  2.88509999e+06,
        -1.09680000e+06],
       [-1.02015733e+07,  1.27509666e+06,  2.68274599e+07,
        -1.02007600e+07],
       [-2.28000000e+04,  2.84999999e+03,  5.98999999e+04,
        -2.28000000e+04],
       [-2.37146666e+05,  2.96433333e+04,  6.22944999e+05,
        -2.37145000e+05]])

In [ ]:
#Проверка
np.dot(A, A_inv)

array([[ 9.99993514e-01,  8.11091303e-07,  1.70573823e-05,
        -6.48593925e-06],
       [-1.21519750e-04,  1.00001520e+00,  3.19498505e-04,
        -1.21525903e-04],
       [-1.79798164e-07,  2.24782485e-08,  1.00000047e+00,
        -1.79780236e-07],
       [-9.17861709e-06,  1.14738488e-06,  2.41250731e-05,
         9.99990823e-01]])

In [ ]:
#Числа обусловленности матрицы
print(np.linalg.cond(A, p=1))
print(np.linalg.cond(A, p=np.inf))

28865938592.90533
72709218091.40654


Часть 2

In [ ]:
#Исходные данные
b = np.array([-1,  1,  1, -1,  1, 0]) #Наддиагональ
c = np.array([50,  90,  125,  110,   85,   70]) #Основная диагональ
a = np.array([0, 1,  1, -1,  0,  1]) #Поддиагональ
f = np.array([10,  -9,  12,  11,  9,  8]) #Правая часть

In [ ]:
#Проверка достаточных условий
check = True
for i in range(1,5):
  if abs(c[i]) < abs(b[i]) + abs(a[i]):
    check = False
check

True

In [ ]:
#Реализация метода прогонки
alpha = np.zeros((6))
beta = np.zeros((6))
x = np.zeros((6))

alpha[0] = -1 * b[0] / c[0]
beta[0] = f[0] / c[0]
for i in range(1, 5):
  alpha[i] = (-1 * b[i] / (a[i] * alpha[i-1] + c[i]))
  beta[i] = ((f[i] - a[i] * beta[i-1]) / (a[i]*alpha[i-1] + c[i]))
x[5] = ((f[5] - a[5] * beta[4]) / (c[5] + a[5] * alpha[4])) 
for i in reversed(range(5)):
  x[i] = alpha[i] * x[i+1] + beta[i]
x

array([ 0.19793468, -0.10326607,  0.09601154,  0.10182334,  0.10455539,
        0.11279207])

In [ ]:
#Матрица А
A = np.array([50, 1, 0, 0, 0, 0, -1, 90, 1, 0, 0, 0, 0, 1, 125, -1, 0, 0, 0, 0, 1, 110, 0, 0, 0, 0, 0, -1, 85, 1, 0, 0, 0, 0, 1, 70])
A = A.reshape((6,6))

In [ ]:
#Невязка
n = f.reshape(6, 1) - np.dot(A, x.reshape(6, 1))
n

array([[ 2.06532138e-01],
       [ 3.95869357e-01],
       [ 2.03646671e-01],
       [-2.96578471e-01],
       [ 1.01823336e-01],
       [-1.77635684e-15]])

In [ ]:
#Нормы невязки
print(np.linalg.norm(n, 1))
print(np.linalg.norm(n, np.inf))

1.2044499738262129
0.3958693572353411


In [ ]:
#Сохранение исходного решения и изменение коэффициентов правой части
xv1 = x
f = np.array([10,  -9,  11.99,  11.01,  9,  8]) #Правая часть

In [ ]:
#Решение возмущенной системы
xv2 = x

In [ ]:
#Разность исходного решения и решения возмущенной системы 
(xv1 - xv2).reshape((6,1))

array([[-1.79356978e-08],
       [-8.96784890e-07],
       [ 8.07285758e-05],
       [-9.01751948e-05],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])